// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwgvUtMNDAL2E-e_1rj1yjiyt2zh5EoEI',
    appId: '1:639876446227:web:8e39880c9fe84e617827e6',
    messagingSenderId: '639876446227',
    projectId: 'game-tracker-css',
    authDomain: 'game-tracker-css.firebaseapp.com',
    databaseURL: 'https://game-tracker-css-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'game-tracker-css.firebasestorage.app',
    measurementId: 'G-32TFBY7RXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6nA_oqTIrcT69Poxf3E2155ittfG8Xac',
    appId: '1:639876446227:android:b35a9ce2d8c83bea7827e6',
    messagingSenderId: '639876446227',
    projectId: 'game-tracker-css',
    databaseURL: 'https://game-tracker-css-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'game-tracker-css.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5a6tX4OLPJeWMWzQSov-3XmljwakoUI8',
    appId: '1:639876446227:ios:408afcb378c1f6197827e6',
    messagingSenderId: '639876446227',
    projectId: 'game-tracker-css',
    databaseURL: 'https://game-tracker-css-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'game-tracker-css.firebasestorage.app',
    iosBundleId: 'com.example.cpdFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5a6tX4OLPJeWMWzQSov-3XmljwakoUI8',
    appId: '1:639876446227:ios:408afcb378c1f6197827e6',
    messagingSenderId: '639876446227',
    projectId: 'game-tracker-css',
    databaseURL: 'https://game-tracker-css-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'game-tracker-css.firebasestorage.app',
    iosBundleId: 'com.example.cpdFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwgvUtMNDAL2E-e_1rj1yjiyt2zh5EoEI',
    appId: '1:639876446227:web:1b59113a978a995d7827e6',
    messagingSenderId: '639876446227',
    projectId: 'game-tracker-css',
    authDomain: 'game-tracker-css.firebaseapp.com',
    databaseURL: 'https://game-tracker-css-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'game-tracker-css.firebasestorage.app',
    measurementId: 'G-ZQHFPM7E3N',
  );
}
